#!/usr/bin/env bash

build() {
	day=$(printf 'day%02d' $1)
	echo "> build $day"
	cabal build $day
}

tests() {
	tests_out="./resources/tests/$1.$2.out"
	tests_in="./resources/tests/$1.$2.in"
	echo "> cat \"$tests_out\" : $(cat $tests_out)"
	echo "> run \"$tests_in\"  : $(cabal run $day $2 $tests_in)"
}

solve() {
	input_in="./resources/input/$1.$2.in"
	echo "> run \"$input_in\"  : $(cabal run $day $2 $input_in)"
}

if [[ "$1" == "tests" ]]; then
	echo "===== Day $2 Part $3 ====="
	build $2
	tests $2 $3
elif [[ "$1" == "solve" ]]; then
	echo "===== Day $2 Part $3 ====="
	build $2
	solve $2 $3
else
	echo "===== Day $1 Part $2 ====="
	build $1
	tests $1 $2
	solve $1 $2
fi
